version: 1.2
# this part is optional: if not specified, the internal Postgres-DB will be used (inside Docker container)
database:
  host: gateway.docker.internal
  port: 5432
  dbname: netascore
  on_existing: abort # skip, delete, abort
  # user and password to be specified as ENV variables
# -- end of optional db part --
import:
  type: osm
  filename: austria-latest.osm.pbf
optional:
  dem:
    filename: austria.tif # GeoTIFF
    srid: 31287
  noise:
    filename: noise.gpkg # GeoPackage
    # column_noise: noise # TODO: set from settings file
index:
  compute_explanation: False
profiles:
  -
    profile_name: bike
    filename: profile_bike.yml
    filter_access_bike: True
  -
    profile_name: walk
    filename: profile_walk.yml
    filter_access_walk: True
export:
  type: geopackage
  filename: osm_network.gpkg # GeoPackage: here two layers are included: "edge" including attributes and indexes; "node" including attributes
