services:
  api:
    build: .
    container_name: "${PROJECT_NAME:-citwin-api}"
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - "API_ROOT_PATH=${API_ROOT_PATH:-/}"
    depends_on:
      netascore-db:
        condition: service_healthy
    ports:
      - "${API_PORT:-8000}:8000"
    stdin_open: true
    tty: true

  netascore-db:
    image: postgis/postgis:17-3.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 120
