services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - netascore_data:/app/netascore/data

volumes:
  netascore_data:
    name: netascore_data
