services:
  api:
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./netascore:/netascore
    working_dir: /app
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8000:8000"
