services:
  api:
    build:
      context: .
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
      - .:/app
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NETASCORE_HOST=netascore
      - NETASCORE_COMMAND=data/settings.yml
    ports:
      - "8000:8000"
    depends_on:
      - netascore
    working_dir: /app

  netascore:
    image: plusmobilitylab/netascore:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/usr/src/netascore/data
    command: ["sleep", "infinity"]
    depends_on:
      netascore-db:
        condition: service_healthy

  netascore-db:
    image: postgis/postgis:13-3.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 20s
      retries: 120
