services:
  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      netascore-db:
        condition: service_healthy
    ports:
      - "${API_PORT:-8000}:8000"
    stdin_open: true   # for interactive debugging (docker run -i)
    tty: true          # for pseudo-terminal (docker run -t)

  netascore-db:
    image: postgis/postgis:17-3.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 120
