name: citwin-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.7

  # api
  - fastapi
  - pydantic
  - pydantic-settings
  - python-multipart
  - uvicorn

  # pipeline
  - geopandas
  - networkx
  - numpy
  - pandas
  - pyyaml
  - scikit-learn
  - shapely

  # netascore
  - gdal=3.10.3
  - libgdal=3.10.3
  - psycopg2
  - pyyaml
  - requests
  - pip
  - pip:
    - jinjasql2
    - osm2geojson
