version: 1.2

global:
  case_id: default_case
  target_srid: 0

database:
  host: netascore-db
  port: 5432
  dbname: postgres
  username: postgres
  password: postgres
  on_existing: delete

import:
  type: osm
  on_existing: delete
  bbox: 0.0,0.0,0.0,0.0
  interactive: False
  buffer: 0

index:
  compute_explanation: False

profiles:
  -
    profile_name: bike
    filename: profile_bike.yml
    filter_access_bike: True
  -
    profile_name: walk
    filename: profile_walk.yml
    filter_access_walk: True

export:
  type: geopackage
  filename: netascore_<case_id>.gpkg
